[options]
admin_passwd = skyline-local-master
db_host = odoo-db
db_port = 5432
db_user = odoo
db_password = odoo
list_db = True
proxy_mode = False
without_demo = False
smtp_server = mailpit
smtp_port = 1025
smtp_ssl = False
email_from = sponsorship@skyline.local
